steps:
  # Step 1 — Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.frontend'
      - '-t'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'
      - '-t'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:latest'
      - '.'

  # Step 2 — Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'

  # Step 3 — Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:latest'

  # Step 4 — Create a new instance template for container image
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instance-templates create vf-frontend-template-$BUILD_ID \
          --container-image=asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID

  # Step 5 — Update MIG to new template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instance-groups managed set-instance-template vf-frontend-mig \
          --template=vf-frontend-template-$BUILD_ID \
          --zone=asia-south1-c

  # Step 6 — Rolling update
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud compute instance-groups managed rolling-action start-update vf-frontend-mig \
          --version=template=vf-frontend-template-$BUILD_ID \
          --zone=asia-south1-c \
          --max-surge=1 \
          --max-unavailable=0

images:
  - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'
  - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
