steps:
  # Step 1 — Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.frontend'
      - '-t'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'
      - '-t'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:latest'
      - '.'

  # Step 2 — Push Docker images
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:latest'

  # Step 3 — Create new instance template using COS and startup script
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: gcloud
    args:
      - compute
      - instance-templates
      - create
      - vf-frontend-template-$BUILD_ID
      - --image-family=cos-stable
      - --image-project=cos-cloud
      - --metadata=startup-script=#! /bin/bash
        docker-logout.sh && \
        docker-credential-gcr configure-docker && \
        docker pull asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID && \
        docker stop frontend || true && \
        docker rm frontend || true && \
        docker run -d --name frontend -p 80:80 asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID

  # Step 4 — Update MIG to use new template
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: gcloud
    args:
      - compute
      - instance-groups
      - managed
      - rolling-action
      - start-update
      - vf-frontend-mig
      - --version=template=vf-frontend-template-$BUILD_ID
      - --zone=asia-south1-c
      - --max-surge=1
      - --max-unavailable=0

images:
  - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'
  - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:latest'

options:
  logging: CLOUD_LOGGING_ONLY
