# cloudbuild-frontend.yaml — Frontend with custom VPC (no template creation, versioned images)
steps:
  # Step 1 — Build Docker image with BUILD_ID
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-f'
      - 'Dockerfile.frontend'
      - '-t'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'
      - '.'

  # Step 2 — Push BUILD_ID tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'

images:
  - 'asia-south1-docker.pkg.dev/emerald-state-491204-b8/capstone-demo-artifact/vf-frontend:$BUILD_ID'

options:
  logging: CLOUD_LOGGING_ONLY
