# Use official Python image
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy service code
COPY . .
COPY ../common ./common

# Expose port
EXPOSE 5001

# Run the app
CMD ["python", "app.py"]
